### ISSUE TITLE
[alert/alias] Exception when adding new alias which is an existing user

### ISSUE THREAD

**Issue by Clam-** [Clam-/pyBurlyBot#77]
```
(05:19:52) <@Clam> .alias poop stoopdahome  
(05:19:53) <@bbm> OperationalError: no such column: user.   File "/home/bbm/pyBurlyBot/modules/pbm_alias.py", line 291, in alias.     return aliasuser(bot, arg1, arg2, source). |   File "/home/bbm/pyBurlyBot/modules/pbm_alias.py", line 234, in aliasuser.     USERS_MODULE._rename_user(bot.network, target, source). 
```

Looks like it's related to alert module:

```
2016-12-26 12:19:54-0600 [BurlyBot (TLSMemoryBIOProtocol),client] Exception with: ('UPDATE alert SET user=? WHERE user=?;', (u'stoopdapoop', u'stoopdahome'))
2016-12-26 12:19:54-0600 [-] Traceback (most recent call last):
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/opt/lib/python2.7/threading.py", line 783, in __bootstrap
2016-12-26 12:19:54-0600 [-]     self.__bootstrap_inner()
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2016-12-26 12:19:54-0600 [-]     self.run()
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/opt/lib/python2.7/threading.py", line 763, in run
2016-12-26 12:19:54-0600 [-]     self.__target(*self.__args, **self.__kwargs)
2016-12-26 12:19:54-0600 [-] --- <exception caught here> ---
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
2016-12-26 12:19:54-0600 [-]     result = context.call(ctx, function, *args, **kwargs)
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
2016-12-26 12:19:54-0600 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
2016-12-26 12:19:54-0600 [-]     return func(*args,**kw)
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/pyBurlyBot/modules/pbm_alias.py", line 291, in alias
2016-12-26 12:19:54-0600 [-]     return aliasuser(bot, arg1, arg2, source)
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/pyBurlyBot/modules/pbm_alias.py", line 234, in aliasuser
2016-12-26 12:19:54-0600 [-]     USERS_MODULE._rename_user(bot.network, target, source)
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/pyBurlyBot/modules/pbm_users.py", line 116, in _rename_user
2016-12-26 12:19:54-0600 [-]     Settings.databasemanager.batch(network, qs)
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/pyBurlyBot/util/db.py", line 39, in batch
2016-12-26 12:19:54-0600 [-]     return db.batch(qs)
2016-12-26 12:19:54-0600 [-]   File "/home/bbm/pyBurlyBot/util/db.py", line 210, in batch
2016-12-26 12:19:54-0600 [-]     raise result
2016-12-26 12:19:54-0600 [-] sqlite3.OperationalError: no such column: user
```

Looks like the user-rename handler has been copy pasted without adjusting for the alert's table configuration https://github.com/Clam-/pyBurlyBot/blob/master/modules/pbm_alert.py#L221

**Comment by gkistler** [comment]
Fixed in 1f1baaf318db3a010623d44655023e7e4ce38574
